### ISSUE TITLE
iTerm2 not picking up half keyboard

### ISSUE THREAD

**Issue by betai** [ZevEisenberg/Keyb#26]
For some reason I'm not able to use half keyboard in iTerm for some reason.
https://www.loom.com/share/1a0804ffb7e642faba324b4ee51fdc71
I'm on OSX 12.1 and iTerm 3.4.12
I tried using KeyCastr to show my keystrokes in the video but they didn't seem to pick up while I was in iTerm as you can see in the bottom left corner
Am I missing some kind of preferences?

**Comment by ZevEisenberg** [comment]
Thanks for the report. There's no setting in Keyb you're missing; it must be some incompatibility with the way iTerm2 is handling key input. Fortunately, they're both open source, so I should be able to debug it if I have time. I've been thinking of trying iTerm2 for its better dark mode support anyway 🤔

**Comment by betai** [comment]
Fwiw, it works on iTerm on my work laptop running the same OS and iterm 3.4.15 (I tried updating my personal computer to 3.4.15 with no luck)

**Comment by ZevEisenberg** [comment]
Interesting, that suggests maybe there's some kind of configuration or permission difference? A preference in iTerm that's different between the two machines? I did a quick test locally and was not able to reproduce the issue. iTerm 3.4.15, macOS 12.1 (21C52).

**Comment by betai** [comment]
I'm now noticing that it not only doesn't get picked up in the terminal, but doesn't even get picked up in the iTerm preferences either:
https://www.dropbox.com/s/4d2huzefkbedj4h/Screen%20Recording%202022-08-30%20at%2021.48.54.mov?dl=0
(my attempt to write hello world in the shell and the preferences)
I guess I'm just curious what makes the app work? The OS is constantly listening for my keystrokes, but what allows your app to run on another app? What permissions do I need to allow? I'm running iTerm 3.4.16 and OSX 12.5

**Comment by ZevEisenberg** [comment]
Interesting. The app requires accessibility permissions to work. You could try toggling those permissions off and on again, and restarting Keyb, and seeing if that helps. Under the hood, it's using a [`CGEvent` tap](https://developer.apple.com/documentation/coregraphics/cgevent/1454426-tapcreate) to get access to keyboard events.
